### ISSUE TITLE
[Feature Request] Data source for GET /repos/:owner/:repo/collaborators

### ISSUE THREAD

**Issue by james-algolift** [terraform-providers/terraform-provider-github#103]
Hi,

I'm hoping to gain some traction on a feature to provide a data source for the list of collaborators: https://developer.github.com/v3/repos/collaborators/#list-collaborators

One highly useful use case of this is to be stateful about all repository collaborator public keys. This endpoint includes org members, members of attached teams, outside collaborators, and their permissions. There are workarounds, but none quite as satisfactory as would be a de-facto feature provided here.

Thanks for your consideration!

**Comment by megan07** [comment]
Thanks @james-algolift  for opening this issue. It's been closed with #236 and will be released shortly.
