### ISSUE TITLE
Can't set the number of reviewers when using the github_branch_protection resource

### ISSUE THREAD

**Issue by damascenorakuten** [terraform-providers/terraform-provider-github#156]
Hello, we would like to change the number of reviewers from 1 (default) to 2, but that's not currently possible.

### Terraform Version
```
terraform --version
Terraform v0.11.8
+ provider.consul v2.1.0
+ provider.external v1.0.0
+ provider.github v1.3.0
```

### Affected Resource(s)
Resource:
- github_branch_protection

### Terraform Configuration Files
```
resource "github_branch_protection" "stinson" {
  repository = "${github_repository.stinson.name}"
  branch = "master"
  enforce_admins = true

  required_status_checks {
    strict = false
    contexts = ["continuous-integration/branch", "codeclimate"]
  }

  required_pull_request_reviews {
    dismiss_stale_reviews = true
    include_admins = true
  }
}
```

### Expected Behavior
We should be able to change the number of reviewers, but we can't. There should be a parameter to set that.

### Actual Behavior
It sets the number of reviewers to one. Check the terraform plan output:
```
  + github_branch_protection.stinson
      id:                                                    <computed>
      branch:                                                "master"
      enforce_admins:                                        "true"
      etag:                                                  <computed>
      repository:                                            "stinson"
      required_pull_request_reviews.#:                       "1"
      required_pull_request_reviews.0.dismiss_stale_reviews: "true"
      required_status_checks.#:                              "1"
      required_status_checks.0.contexts.#:                   "2"
      required_status_checks.0.contexts.201666563:           "codeclimate"
      required_status_checks.0.contexts.2787379639:          "continuous-integration/branch"
      required_status_checks.0.strict:                       "false"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create the resource github_branch_protection
2. Run `terraform plan`
3. Run `terraform apply`
4. Check the Settings of your repository:
<img width="587" alt="screen shot 2018-09-18 at 10 40 47" src="https://user-images.githubusercontent.com/30900555/45675343-770d0880-bb2f-11e8-9643-05ae2001f444.png">

**Comment by damascenorakuten** [comment]
@joebowbeer thanks for your reply. I just realized there's already a request for that [here](https://github.com/terraform-providers/terraform-provider-github/issues/89), should I simply close this issue?

**Comment by joebowbeer** [comment]
#89 Yeah, I just realized it as well and was going to update my comment

I think this should be closed as a dup

**Comment by damascenorakuten** [comment]
Great! Closing it then, thanks.
