### ISSUE TITLE
Support Github Actions

### ISSUE THREAD

**Issue by cemo** [terraform-providers/terraform-provider-github#162]
Please support Github Actions.

**Comment by paultyng** [comment]
If you are talking about setting them up on a repository, that is managed by a file in the repository, so I don't think its something that you would do via the API.

**Comment by kevinburkemeter** [comment]
Any chance we can leave this issue open, in case Github adds support for it? I want to subscribe to something, so I get an email in case the status of support changes.

**Comment by timvisher** [comment]
@paultyng This apparently shipped (in beta at least) since this was opened. https://developer.github.com/v3/actions/

**Comment by paultyng** [comment]
Oh interesting, it does look like the only things with full crud are some of the self hosted runner registration and secrets management though. Not workflows. I'll reopen this.

**Comment by timvisher** [comment]
I found this issue because I was wondering how I could manage secrets so that's the relevant bit for me. I think your point earlier about workflows being managed by code in the repo still stands. It's the surround configuration that would be interesting to manage otherwise. :)

**Comment by jcudit** [comment]
There is work in progress over in https://github.com/terraform-providers/terraform-provider-github/issues/271 for the `Secrets` subcomponent of Actions.

Our underlying library has broken up Actions support into [various subcomponents](https://github.com/google/go-github/issues/1399#issuecomment-579554516) as well.  This issue can track the overall consumption of Actions features as needed.

**Comment by NishkarshRaj** [comment]
I am working on a private repository where I have managed to set up terraform installation, AWS user authentication and started work on launching EC2 instance using Dockerfile Actions.
Someone wants to contribute, I can add you to my private repository or even share my work here.

**Comment by Ynniss** [comment]
@NishkarshRaj  i'm a complete beginner on terraform and github actions, but i'd love to see what you've done.
Feel free to invite me, or to make the repository public :)

**Comment by jcudit** [comment]
Actions are supported via the `github_repository_file` resource.  Please re-open with more details if a more tailored resource is needed going forward.
