### ISSUE TITLE
Support renaming of repositories

### ISSUE THREAD

**Issue by sclausson** [terraform-providers/terraform-provider-github#17]
### Terraform Version
v0.9.6

### Affected Resource(s)
- github_repository

### Description
If I need to rename a repository, then I would like to be able to change the name without forcing a new resource. Forcing a new resource results in the deletion of the existing repository, including all code, branches, etc. 

### Steps to reproduce
Changing:
```hcl
resource "github_repository" "fruit" {
  name = "apples-and-oranges"
}
```
To:
```hcl
resource "github_repository" "fruit" {
  name = "apples-and-pears"
}
```
Results in:
```sh
-/+ github_repository.fruit
...
      name:   "apples-and-oranges" => "apples-and-pears" (forces new resource)
```

**Comment by radeksimko** [comment]
Hi @sclausson ,
unfortunately there doesn't seem to be API method for renaming a repo:
https://developer.github.com/v3/repos/

Until (if ever) there's an API & SDK support I'd recommend renaming the repo manually via UI per https://help.github.com/articles/renaming-a-repository/ and then following the steps below to reflect this change in Terraform config:

```sh
terraform state rm github_repository.fruit
# change name of the repo in the config
terraform import github_repository.fruit apples-and-pears
```

Hope it helps.

I'm going to close this issue as there is nothing we can do at this point in the codebase IMO, but do let me know if I'm mistaken and feel free to suggest specific solutions/improvements to address this problem better.

**Comment by sclausson** [comment]
Makes sense. Thanks for the explanation.
