### ISSUE TITLE
Renaming labels creates new labels.

### ISSUE THREAD

**Issue by eliasbrange** [terraform-providers/terraform-provider-github#173]
Terraform version: v0.11.8
Provider version: v1.3.0

# Problem

It seems like when changing the name property on a label the provider creates a new label with the new name and leaves the old one intact. 

# Cause

The reason for this is due to the implementation in https://github.com/terraform-providers/terraform-provider-github/blob/master/github/resource_github_issue_label.go.

In `resourceGithubIssueLabelCreateOrUpdate` the following flow is used:

Check if `newName` is a label, if it is update it and if it isn't create a new one. The problem here is that the original name is not the one that is checked. So if a label is changed in terraform from `label1` and `label2`, github is searched for `label2`, which does not exist yet so a new label is created and the old `label1` is left behind.

# Solution

When checking for existence, the original name should be used.

**Comment by kuwas** [comment]
Would be ideal if there was an authoritative labels resource, using something like the dynamic blocks introduced in 0.12, each block is a label. Any labels not found in the supplied list will be removed.

**Comment by php-coder** [comment]
It would be great to get it fixed given that there are already 2 PRs for that.
