### ISSUE TITLE
404 creating repo and adding a collaborator 

### ISSUE THREAD

**Issue by Rizbe** [terraform-providers/terraform-provider-github#176]
### Terraform Version
```
terraform -v
Terraform v0.11.10
+ provider.github v1.3.0
```

### Affected Resource(s)
- github_repository_collaborator

### Terraform Configuration Files
```hcl
resource "github_repository" "foo" {
  name        = "foo"
  private     = true
  description = ""
  has_wiki    = "true"
  has_downloads = "true"
  has_issues  = "true"
}

resource github_repository_collaborator "foo-foo" {
  repository = "foo"
  username   = "foo"
  permission = "push"
}
```

### Debug Output
```
* github_repository_collaborator.foo-foo: PUT https://api.github.com/repos/ORG/foo/collaborators/foo: 404 Not Found []
```

### Expected Behavior
Created the repo foo and add the user foo as a collaborator 

### Actual Behavior
Created the repo foo but when it went to add the user, it got a 404 because it thinks the repo does not exist 
### Steps to Reproduce
1. `terraform apply`

**Comment by MFProduction** [comment]
+1

**Comment by MFProduction** [comment]
I found my error. I was trying to set repo name with the output from .full_name which gave me the error because the full name has organization before repo name: `org/repo` and you just need `repo`

**Comment by megan07** [comment]
Hi @Rizbe !

Thank you for submitting this issue.  I think you may be hitting a race condition as the `github_repository_collaborator` is being created in parallel with the `github_repository`.  I would suggest you read the `github_repository` name into the `github_repository_collaborator` resource like this `repository = ${github_repository.foo.name}`

Please let me know if you have further questions!

Thanks!

**Comment by isen-ng** [comment]
I found the problem and it's not easily solvable without Github's intervention.

To add a user as a collaborator to a repo, the current logged in user (through OAuth or PAT) must already have admin access to the repo.
