### ISSUE TITLE
Support `enforce_admins` API schema in Github Branch Protection

### ISSUE THREAD

**Issue by mechastorm** [terraform-providers/terraform-provider-github#18]
Just wanted to make sure that during the provider switch, that this issue is captured

https://github.com/hashicorp/terraform/pull/14195 (WIP: Migrate include_admins to enforce_admins in Github API )

Has the issue above been fixed in this new repo?

Thanks

**Comment by grubernaut** [comment]
Hey @mechastorm, currently working on this one, should have a fix shortly for you. Thanks!

**Comment by grubernaut** [comment]
Currently we're blocked on this regression fix until this https://github.com/google/go-github/pull/637 is merged and accepted. 
cc: @shurcooL + @gmlewis with a polite ping :heart: 

However, in the meantime we can loosely update branch protection with the new `enforce_admins` field for now. We just won't be able to fully fill out `required_pull_request_reviews`.

**Comment by mechastorm** [comment]
Looks like https://github.com/google/go-github/pull/637 finally got merged!~ :D

**Comment by grubernaut** [comment]
@mechastorm absolutely did! checkout #26. :smile:
