### ISSUE TITLE
[FEATURE REQUEST] Add Support for Repository Projects

### ISSUE THREAD

**Issue by pantocrator27** [terraform-providers/terraform-provider-github#19]
GitHub has an option for managing projects in a repository:

```
Project boards on GitHub help you organize and prioritize your work. You can create project boards for specific feature work, comprehensive roadmaps, or even release checklists.
```

It would be nice to add support for this

**Comment by pantocrator27** [comment]
Please see https://developer.github.com/v3/repos/#create

**Comment by chrisferry** [comment]
Looks like this commit adds that capability.
https://github.com/terraform-providers/terraform-provider-github/commit/4ace080d66ba0f0b073dd5002f605acb134443d2
Maybe we can close this?

**Comment by chrisferry** [comment]
@Nklya It's not clear from his link above as he references the repos "create" not the projects "create".  If @pantocrator27 wants projects created via this provider he should have referenced: https://developer.github.com/v3/projects/#create-a-repository-project
@pantocrator27 Can you clarify what you want exactly?  Thanks

**Comment by pantocrator27** [comment]
@chrisferry my bad ... https://developer.github.com/v3/projects/#create-a-repository-project is the correct URL.
