### ISSUE TITLE
[BUG] Cannot switch default branch back to master

### ISSUE THREAD

**Issue by liamg-form3** [terraform-providers/terraform-provider-github#193]
Switching default branch to something other than master, then attempting to switch it back to master again results in success being reported, but the default branch not changing back to master.

Problem is here: https://github.com/terraform-providers/terraform-provider-github/blob/master/github/resource_github_repository.go#L248 - it will only ever update default branch if it's NOT `master`.

### Terraform Version
Terraform v0.11.11
+ provider.github v1.3.0

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "main" {
    name          = "my-repo-12345"
    private       = true
    auto_init     = true
}
```

then create `develop` branch and:

```hcl
resource "github_repository" "main" {
    name           = "my-repo-12345"
    private        = true
    auto_init      = true
    default_branch = "develop"
}
```

then:

```hcl
resource "github_repository" "main" {
    name           = "my-repo-12345"
    private        = true
    auto_init      = true
    default_branch = "master"
}
```

### Expected Behavior
Default branch should be switched back to master once the third step above is run.

### Actual Behavior
Default branch is left as `develop`.

### Steps to Reproduce
See config files above.

**Comment by joscha** [comment]
This still seems to happen on:
```
Terraform v0.12.9
+ provider.github v2.2.1
```

any chance we can get this merged? It's almost nearing it's birthday :)

**Comment by emma-sax4** [comment]
👍 to this bug! We should merge the pull request as soon as possible: https://github.com/terraform-providers/terraform-provider-github/pull/194.

**Comment by DazKins** [comment]
Any update on this fix being merged?

**Comment by jcudit** [comment]
Makes sense to group this into related work around branch naming that is already planned for the next release.  I think we can get a fix shipped by end of month.
