### ISSUE TITLE
404 when creating repo and adding team permissions

### ISSUE THREAD

**Issue by drpebcak** [terraform-providers/terraform-provider-github#195]
### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
- github_repository
- github_team_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "foo" {
  name        = "foo"
  private     = true
  description = "foo repo"
  has_wiki    = "true"
  has_downloads = "true"
  has_projects = "false"
  allow_merge_commit = "false"
  allow_rebase_merge = "false"
  archived    = "false"
  has_issues  = "false"
}

resource "github_team_repository" "ReadOnly-foo" {
  team_id    = "${github_team.ReadOnly.id}"
  repository = "foo"
  permission = "pull"
}
```

### Expected Behavior
It should have created the repository and then added team permissions

### Actual Behavior
It creates the repository, but then 404s when trying to add team membership. When the terraform is ran a second time, it succeeds.

```
00:01:56.035 1 error(s) occurred:
00:01:56.035 
00:01:56.035 * github_team_repository.ReadOnly-foo: 1 error(s) occurred:
00:01:56.035 
00:01:56.036 * github_team_repository.ReadOnly-foo: PUT https://api.github.com/teams/0000000/repos/MYORG/foo: 404 Not Found []
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
I think this is similar to #176, although in my case I am not setting the repo name based on output from another resource. Potentially that is the problem because TF does not know the relationship between the two resources, but from the docs there is not an exported attribute I could use to set `name` inside my `github_team_repository` resource.

**Comment by majormoses** [comment]
Does running it a second time or pre-creating the repository work? What version are you using? The reason I ask is that I have been using this provider in my modules quite a bit and I dont see this behavior. I validated that I did not have any explicit dependency in place forcing the behavior to avoid that. Is it possible that your token does not have the appropriate oauth scopes attached to it? Github typically returns 400s when something was denied or not found. This makes it harder for an attacker to know whether they found a resource worth pursuing. It obviously has it's downsides as it can make it harder to debug authorization issues.

**Comment by drpebcak** [comment]
It works when running the second time, or if I’m managing a repo that already existed. It doesn’t always happen either - it seems to me like a case where the api is being ‘eventually consistent.’

**Comment by majormoses** [comment]
Interesting, Do you have any metrics on how often it fails? I have created hundreds of repos and assigning repo team permissions like this without encountering. I am not trying to minimize your pain I am just trying to understand how/when it happens as I have so far been unable to replicate.

**Comment by drpebcak** [comment]
Unfortunately nothing super meaningful. I imported a bunch of existing repos, and have only had to create a few new ones from scratch. I’d say in my experience it fails most of the time, but I’d have to try it a bunch more times before I could give any real stats.

**Comment by megan07** [comment]
Hi @drpebcak !

Thank you for submitting this issue.  I think you may be hitting a race condition as the `github_team_repository` is being created in parallel with the `github_repository`.  I would suggest you read the `github_repository` name into the `github_team_repository` resource like this `repository = ${github_repository.foo.name}` and see if it works consistently.

You should be able to use any of the arguments passed in as attributes that are exported.

Please let me know if you have further questions!
Thanks!

**Comment by drpebcak** [comment]
Thanks @megan07. I'm not actually using this anymore so I'll go ahead and close this issue.
