### ISSUE TITLE
Terraform Import is missing attribute has_projects

### ISSUE THREAD

**Issue by troyfontaine** [terraform-providers/terraform-provider-github#229]
### Terraform Version
0.11.14

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
provider "github" {
  token        = "${var.github_token}"
  organization = "${var.github_organization}"
  version = "~> 2.1"
}

resource "github_repository" "import" {
    has_projects = "false"
}
```

### Expected Behavior
When running import of an existing github repository, the attribute `has_projects` should be imported into the state file.

### Actual Behavior
When running import of an existing github repository, the attribute `has_projects` is missing from the state file.  When you then run terraform plan, terraform wants to modify the configuration of the repo when it isn't required.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import github_repository.import my_repo_name`
2. `terraform plan`

### Important Factoids
None

### References
None

**Comment by megan07** [comment]
Thanks @troyfontaine for opening this issue. It's been closed with #237 and will be released shortly.
