### ISSUE TITLE
Remove auth requirement for provider

### ISSUE THREAD

**Issue by julianvmodesto** [terraform-providers/terraform-provider-github#230]
I'd like to consume only the [github_ip_ranges](https://www.terraform.io/docs/providers/github/d/ip_ranges.html) data source, but the provider requires setting an Organization and Token.

Would it be possible to remove this requirement?

**Comment by majormoses** [comment]
duplicate of #190  and proposed as #191

**Comment by tracypholmes** [comment]
Hi, @julianvmodesto! Thank you for opening this issue. This is being closed as a duplicate of #190.
