### ISSUE TITLE
required_approving_review_count parameter is not documented

### ISSUE THREAD

**Issue by mrwacky42** [terraform-providers/terraform-provider-github#233]
### Terraform Version
```
$terraform -v
Terraform v0.11.11
+ provider.github v2.1.0
+ provider.null v2.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "branches" {
  count          = "${length(var.protected_branches)}"
  repository     = "${var.name}"
  branch         = "${var.protected_branches[count.index]}"
  enforce_admins = "${var.enforce_admins}"

  required_status_checks {
    strict   = "${var.required_status_checks}"
    contexts = "${var.required_status_checks_context}"
  }

  required_pull_request_reviews {
    dismiss_stale_reviews      = "${var.dismiss_stale_reviews}"
    require_code_owner_reviews = "${var.require_code_owner_reviews}"
  }
}
```

### Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
```
  ~ module.some_repo.github_branch_protection.branches
      required_pull_request_reviews.0.required_approving_review_count: "" => "1"
```

### Expected Behavior
This is probably expected, but the feature is not documented.
We would expect this to be in the provider docs
https://www.terraform.io/docs/providers/github/r/branch_protection.html

### Actual Behavior
We are testing an upgrade to the newest provider - from v1.1 to v2.1, and the provider is setting a bunch of previously unset values to `1`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` on any update from v1.1.0 to v2.1.0 with no code changes.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #181

**Comment by aeschright** [comment]
Closed by #220
