### ISSUE TITLE
[Feature Request] Create repo from template repo

### ISSUE THREAD

**Issue by veggiemonk** [terraform-providers/terraform-provider-github#254]
Hi,

While trying to create a repository from a template, we realized the resource "github_repository" doesn't allow to create from template repository.

The feature has been announced here: https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

The process can be done manually by just going to `https://github.com/myorg/template-repo/generate` and filling the form.

How much work would it require to implement that feature here? 
I can spend some time doing that but I would really appreciate some guidance.

Thank you

**Comment by carinadigital** [comment]
Look at the terraform provider docs https://www.terraform.io/docs/extend/writing-custom-providers.html
And then for github look at https://developer.github.com/v3/repos/#create-repository-using-a-repository-template

**Comment by jkenn99** [comment]
This is implemented in go-github https://github.com/google/go-github/blob/v28.0.1/github/repos.go#L352-L371

**Comment by jcudit** [comment]
I've got a local branch implementing this feature with a passing test:

```
$ go test -v -timeout 30m  ./... -run TestAccGithubRepository_createFromTemplate
?   	github.com/terraform-providers/terraform-provider-github	[no test files]
=== RUN   TestAccGithubRepository_createFromTemplate
=== PAUSE TestAccGithubRepository_createFromTemplate
=== CONT  TestAccGithubRepository_createFromTemplate
--- PASS: TestAccGithubRepository_createFromTemplate (8.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-github/github	9.041s
```

I'm blocked on onboarding at the moment but plan on getting a PR associated with this issue once  I have access to publish my branch.

**Comment by willejs** [comment]
@jcudit thats great! I had done a similar thing and was just about to write a test and push it. Would be good to see this get merged in.

**Comment by jcudit** [comment]
@willejs see the linked PR above ☝️ .  Feedback is welcome if you've got the time.
