### ISSUE TITLE
Feature request: support deleting head branch of Github pull requests

### ISSUE THREAD

**Issue by vinniegarcia** [terraform-providers/terraform-provider-github#264]
Requesting that you support the new feature to automatically delete the head branch of pull requests that Github just announced here: https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches. A small thing but it saves manual effort. Thanks in advance!

**Comment by TomTucka** [comment]
Happy to do this as soon as `go-github` support it, I raised an issue over on their repository: https://github.com/google/go-github/issues/1245

**Comment by skeggse** [comment]
Cross-linking for reference: https://github.com/google/go-github/pull/1388

**Comment by jakebiesinger-onduo** [comment]
This is now available in go-github v29. I have a PR for the corresponding `terraform-provider-github` changes, but I don't know how to update the `vendor` directory there. Any pointers?

**Comment by springerigor** [comment]
@jakebiesinger-onduo Please try with `go mod vendor`.

**Comment by jakebiesinger-onduo** [comment]
Thanks, @springerigor. I've opened #342 though there are still a few issues with the PR.

**Comment by TomTucka** [comment]
Can someone assign this to me? I'll get it finished this week

**Comment by jspiro** [comment]
Would still love to see this if it's possible :)

**Comment by gevalter** [comment]
We also waiting for this feature, tell me if i can help
