### ISSUE TITLE
github_team_repository permission field do not accept "maintain"

### ISSUE THREAD

**Issue by Ameausoone** [terraform-providers/terraform-provider-github#270]
### Terraform Version

Terraform v0.11.14
provider.github v2.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- github_team_repository

### Terraform Configuration Files
```hcl
resource "github_team_repository" "team_developers" {
  team_id = "${github_team.team.id}"
  repository = "my-repo"
  permission = "maintain"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
We expect to assign "maintain" role on repository for specified team.

### Actual Behavior
But this role is still in beta, it doesn't seem to be available through api => https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator.

I got this (expected) error: 

```
Error: github_team_repository.team_developers: maintain is an invalid value for argument permission
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I think it will be available once maintain feature will be released, I create this issue to follow when it will be available. 

### References
* api reference : https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator
* Terraform documentation : https://www.terraform.io/docs/providers/github/r/team_repository.html

**Comment by alexbde** [comment]
As stated in #296 this feature is out of beta / generally available: https://github.blog/2019-10-03-delegate-responsibilities-with-expanded-repository-permissions/

**Comment by Ameausoone** [comment]
OK I close this issue, duplicate with #296  thx @alexbde
