### ISSUE TITLE
New resource: Github Pubsubhubbub subscription

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-github#275]
It would be nice if this provider supported [Pubsubhubbub](https://developer.github.com/v3/repos/hooks/#pubsubhubbub) subscriptions. For example, I've run into a situation with a monorepo and a bunch of environments with their own webhooks where we've hit the 20-hooks-per-repo limit, and I think it would be possible to get that working again with Pubsubhubbub configuration instead.

This would mean a new resource type according to the description below.

I could tackle implementing this, if there is any chance to get it merged (i.e. if you, the maintainers, don't think it's an inherently bad idea for some reason).

```hcl
# config matching that of https://developer.github.com/v3/repos/hooks/#pubsubhubbub
resource "github_pubsubhubbub_subscription" "ping_me" {
    repo       = ":owner/:repo"
    event_type = "push"
    callback   = "http://postbin.org/123"
    # also supports
    # hmac_secret = "123456"
}
```

**Comment by jcudit** [comment]
@tomasaschan sorry for the delay here.  This would likely ship in the next feature release if a PR was raised.

**Comment by tomasaschan** [comment]
Heh. I've switched jobs and am not using Terraform anymore, so I don't have any need for this now. Leaving it open in case someone else comes looking for it :)
