### ISSUE TITLE
Repository: name already exists on this account

### ISSUE THREAD

**Issue by hazcod** [terraform-providers/terraform-provider-github#278]
### Terraform Version
`Terraform v0.12.8`

### Affected Resource(s)
- github_repository (all of them)

### Terraform Configuration Files
https://github.com/ironPeakServices/infrastructure/blob/master/modules/github/repositories.tf

### Debug Output
```
 Error: POST https://api.github.com/orgs/***/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already e***ists on this account}]

  on modules/github/repositories.tf line 79, in resource "github_repository" "iron-redis":
  79: resource "github_repository" "iron-redis" {



Error: POST https://api.github.com/orgs/***/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already e***ists on this account}]

  on modules/github/repositories.tf line 96, in resource "github_repository" "iron-static":
  96: resource "github_repository" "iron-static" {



Error: POST https://api.github.com/orgs/***/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already e***ists on this account}]

  on modules/github/repositories.tf line 111, in resource "github_repository" "ironpeak--be":
 111: resource "github_repository" "ironpeak--be" {
```

### Panic Output
n/a

### Expected Behavior
Repositories created or reported as already existing, just added to state.

### Actual Behavior
The code errors out with 'repository name already exists'.

### Steps to Reproduce
1.  have already existing github org + account + repos
2. start with fresh terraform plan
3. terraform apply

### Important Factoids
n/a

### References
repo: https://github.com/ironPeakServices/infrastructure/

**Comment by c-knowles** [comment]
Have you tried a command like `terraform import github_repository.iron-redis iron-redis`? Not sure automated import is usually provided by providers.

**Comment by hazcod** [comment]
The original content was generated by https://github.com/GoogleCloudPlatform/terraformer FYI.

**Comment by c-knowles** [comment]
Sounds like the terraformer project might not support the tfstate import properly for this case, not used it before so a bit unsure. Looks interesting though, will try it out.

**Comment by sergeylanzman** [comment]
@hazcod If you imported with terraformer before v0.8? version 0.8 support terraform 0.12

**Comment by hazcod** [comment]
Can confirm this works with latest `terraformer`.
