### ISSUE TITLE
Extra permissions required

### ISSUE THREAD

**Issue by liamg** [terraform-providers/terraform-provider-github#279]
We require the use of the `triage` permission, which is currently still in beta (see https://help.github.com/en/articles/repository-permission-levels-for-an-organization).

What is the view on supporting beta features? Would you accept a PR to add the beta permissions to `github_team_repository`?

**Comment by iniinikoski** [comment]
Looks like they are out of beta: https://github.blog/2019-10-03-delegate-responsibilities-with-expanded-repository-permissions/

It would be great to have the provider support for new permissions...

**Comment by liamg** [comment]
PR created! Sorry for the delay on this!
