### ISSUE TITLE
Feature Request: add apps to github_branch_protection restrictions

### ISSUE THREAD

**Issue by lsowen** [terraform-providers/terraform-provider-github#281]
The [Branch Protection Api](https://developer.github.com/v3/repos/branches/#update-branch-protection) supports adding applications (`apps`) to the push `restrictions` of the branch protection.  

Currently, the provider only supports `teams` and `users`.  This is useful to allow Github Apps to perform automated merge actions of PRs.

It looks like this became available only very recently: https://developer.github.com/changes/2019-09-05-apps-protected-branches-api/

**Comment by skeggse** [comment]
Looks like support for this in `go-github` landed in https://github.com/google/go-github/pull/1283.

**Comment by anGie44** [comment]
@lsowen looks like this feature was addressed with https://github.com/terraform-providers/terraform-provider-github/pull/297/files :)

**Comment by jcudit** [comment]
Yep, seems like it.  Thanks @anGie44!
