### ISSUE TITLE
Error: rpc error: code = Canceled desc = context canceled 

### ISSUE THREAD

**Issue by hazcod** [terraform-providers/terraform-provider-github#284]
### Terraform Version
hashicorp/terraform-github-actions/init@v0.4.4

### Terraform Configuration Files
https://github.com/ironPeakServices/infrastructure/tree/feat/dockersecurity

### Output
https://github.com/ironPeakServices/infrastructure/pull/9/checks?check_run_id=261962158
https://github.com/ironPeakServices/infrastructure/pull/9/checks?check_run_id=261962158

### Expected Behavior
Plan to work fine.

### Actual Behavior
```
Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing




```

**Comment by JohnRoesler** [comment]
I am seeing this same issue. The provider was working properly - then started throwing these context canceled errors. Any ideas on where to look for the issue?

**Comment by hazcod** [comment]
@john set TF_LOG to TRACE and start digging. :-)
