### ISSUE TITLE
How to update branch protection using Terraform without remote branch in GITHUB?

### ISSUE THREAD

**Issue by jorgetovar** [terraform-providers/terraform-provider-github#287]
### Terraform Version
Terraform v0.12.10
+ provider.github v2.2.1

### Affected Resource(s)

- github_branch_protection

### Expected Behavior
What should have happened?
```
github_branch_protection.foo: Creating...
github_branch_protection.foo: Creation complete after 3s [id=foo:staging]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
### Actual Behavior
What actually happened?
`Error: PUT https://api.github.com/repos/jetprogramming/foo/branches/staging/protection: 404 Branch not found []`

### Steps to Reproduce

```
provider "github" {
  token        = "${var.github_token}"
  organization = "${var.github_organization}"
}

# Protect the CI/CD branch of the foo repository
resource "github_branch_protection" "foo" {
  repository     = "foo"
  branch         = "staging"
  enforce_admins = true

  required_pull_request_reviews {
   required_approving_review_count = 2
  }

}
```

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
https://stackoverflow.com/questions/58466341/how-to-update-branch-protection-using-terraform-without-remote-branch-in-github

**Comment by kpfleming** [comment]
As noted in the answer on StackOverflow, this is not possible: the branch to be protected has to exist before the protection can be enabled for it (and if the branch is removed the protection will be removed too).

**Comment by majormoses** [comment]
I think this is the same ask as #167

**Comment by jcudit** [comment]
The `github_branch` resource as well as the `pattern` option to the `github_branch_protection` resource may help this use case.  Please re-open if more is needed here.
