### ISSUE TITLE
Handling renames of user accounts properly - thoughts?

### ISSUE THREAD

**Issue by kpfleming** [terraform-providers/terraform-provider-github#298]
### Terraform Version
Terraform v0.12.12
+ provider.github v2.2.1

### Affected Resource(s)
github_team_membership

### Expected Behavior
Terraform should not have planned to make a team membership change because the user was already in the team.

### Actual Behavior
Terraform plans to make a team membership change.

### Steps to Reproduce
1. Add a user to a team, and apply the changes.
2. Ask the user to change their username on github.com.
3. Run 'plan', and see that Terraform can no longer see that the user is in the team.

This is clearly caused by the Terraform configuration (and state) being based on the the GitHub user's account name, and not its internal ID number. The name is changeable by the user at any time, but the internal ID number is not. If the user changes their account name, Terraform will attempt to add the *old* account name to the team, which could be very bad if that account name has been grabbed by a different user.

In my mind I can envision some mechanism to import a github_user as *data* (not a resource) and grab its internal ID number, then throughout the rest of the configuration refer to that github_user resource (as is done for teams already) and use the internal ID number in the API calls (and in the stored state). If the user changes their name, there wouldn't be any effect, other than the local configuration file would have the wrong 'name' for that github_user 'data' block.

**Comment by kpfleming** [comment]
After learning more about the internals of Terraform this clearly can't work, because *data* objects are not persisted in the state.

This would mean that we'd need a `github_user` resource instead: it wouldn't be creatable or destroyable (only importable), but would otherwise behave as proposed above.

I'm going to experiment with this shortly.

**Comment by jcudit** [comment]
As discussed over Zoom, let's check back in after a couple of months while the following tasks are worked on:

- [ ] @kpfleming to perform exploration work around a `github_user` resource
- [ ] @kpfleming to explore using the standard testing framework to express the **Steps to Reproduce**
- [ ] @kpfleming to explore writing an unrelated provider to gain experience that would benefit future improvements for this provider
- [ ] @jcudit to get onboarded as a maintainer and guide the above changes towards a suitable release

**Comment by kpfleming** [comment]
I've completed items 1 and 3 from this list; item 2 requires some documentation of the environment require to be able to run the test suite before I can experiment with it.

PR #316 is a nearly-comprehensive attempt to address this issue; it allows the Terraform user to use numeric user IDs for GitHub users in their configuration, even though the GitHub API does not accept them (they are translated back to usernames just before each API call is issued). There is more work to do, but the current state works for my configuration.
