### ISSUE TITLE
github_user data source causing TF panic

### ISSUE THREAD

**Issue by sclausson** [terraform-providers/terraform-provider-github#30]
### Terraform Version
0.9.10

### Affected Resource(s)
- data source github_user

### Terraform Configuration Files
```hcl
provider "github" {}

data "github_user" "snigl" {
  username = "snigl"
}
```

### Panic Output
https://gist.github.com/sclausson/1dda72f7ab4ce4109f5ccd8a9d241c0d

### Expected Behavior
Should return github_user data source info.

### Actual Behavior
Crash!!!
```
[DEBUG] plugin: terraform: panic: runtime error: invalid memory address or nil pointer dereference
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
The crash consistently occurs for some GitHub users: snigl, daseg, betajobot, and tomascarlqvist to name a few examples.

The data source consistently works as expected for other GitHub users: sclausson, antonbabenko, raphink to name a few examples.

So, this works fine
```hcl
provider "github" {}

data "github_user" "antonbabenko" {
  username = "antonbabenko"
}
```

And this crashes
```hcl
provider "github" {}

data "github_user" "daseg" {
  username = "daseg"
}
```

**Comment by raphink** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-github/pull/2/files#diff-e0e67aff9f65b130bb301707a366a36fR129

**Comment by sclausson** [comment]
Thanks @raphink 
I will close and wait for 0.10.x to ship.
