### ISSUE TITLE
[Enhancement] github_team should provide Id

### ISSUE THREAD

**Issue by DWSR** [terraform-providers/terraform-provider-github#32]
I would like to suggest that the GitHub_team data source should provide the id of the team in addition to the currently provided attributes. This would help remove the need to lookup the ID when using teams with other attributes.

**Comment by grubernaut** [comment]
Hey @DWSR, it looks like the `github_team` data source does return the `id` of the team, as specified by the data source's `id` attribute. 

For example: 
```
data "github_team" "foo" {
  slug = "terraform"
}

output "team-id" {
  value = "${data.github_team.foo.id}"
}

```
Yields: 
```
data.github_team.foo: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

team-id = <github_team_id>
```

Going to update the documentation to explicitly state this however.
