### ISSUE TITLE
support configuring repository as a template repository

### ISSUE THREAD

**Issue by skeggse** [terraform-providers/terraform-provider-github#327]
### Terraform Version
N/a

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`

### Terraform Configuration Files
```hcl
resource "github_repository" "repo" {
  name        = "client"
  is_template = true
}
```

### Debug Output
N/a

### Panic Output
N/a

### Expected Behavior
I'd like Terraform to support the template repository feature on the repository end - where the repository is specified as a template for use elsewhere. This is supported in `go-github` per https://github.com/google/go-github/pull/1236.

### Actual Behavior
```sh
Error: Unsupported argument

  on template.tf line 3, in resource "github_repository" "repo":
   2:   is_template = true

An argument named "is_template" is not expected here.
```

### Steps to Reproduce
- `terraform validate`
- `terraform apply`

### Important Factoids
N/a

### References
- https://github.com/google/go-github/pull/1236

**Comment by jcudit** [comment]
cc https://github.com/terraform-providers/terraform-provider-github/issues/327
