### ISSUE TITLE
Add support for delete_branch_on_merge

### ISSUE THREAD

**Issue by jakebiesinger-onduo** [terraform-providers/terraform-provider-github#330]
It would be great to have support for `delete_branch_on_merge`, which was added in `go-github` API v29. You'd have to do a version bump to get there.

### Affected Resource(s)
- github_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "repo" {
  ...
  delete_branch_on_merge = true  # Not possible currently
}
```

Thanks!

**Comment by mwarkentin** [comment]
Dupe of #264 ?

**Comment by jakebiesinger-onduo** [comment]
Yep! Thanks.
