### ISSUE TITLE
[Bug] Terraform panics when fetching lists of team IDs using data.github_team

### ISSUE THREAD

**Issue by DWSR** [terraform-providers/terraform-provider-github#34]
### Terraform Version
0.9.8

### Affected Resource(s)
-data.github_team

### Terraform Configuration Files
https://gist.github.com/DWSR/fa65d22519dfc001ef842ad0a4b7ac75#file-main-tf
https://gist.github.com/DWSR/fa65d22519dfc001ef842ad0a4b7ac75#file-variables-tf
https://gist.github.com/DWSR/fa65d22519dfc001ef842ad0a4b7ac75#file-variables-tf

### Debug Output
https://gist.github.com/DWSR/fa65d22519dfc001ef842ad0a4b7ac75#file-terraform-log

### Panic Output
https://gist.github.com/DWSR/fa65d22519dfc001ef842ad0a4b7ac75#file-crash-log

### Expected Behavior
Terraform should return a list of IDs from teams specified in the list `members`

### Actual Behavior
Terraform derped.

**Comment by DWSR** [comment]
This issue seems to be fixed with the latest version of the provider.

**Comment by stack72** [comment]
Thanks for closing this out @DWSR :)
