### ISSUE TITLE
[Feature Request] manage hubVirtualNetworkConnections on virtual hub

### ISSUE THREAD

**Issue by adamalex** [terraform-providers/terraform-provider-github#346]
### Terraform Version
Terraform v0.12.20

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_hub

### Expected Behavior
We would like to be able to manage `hubVirtualNetworkConnections` on a virtual hub via terraform

### Actual Behavior
This does not seem to be supported in the terraform provider

### Important Factoids
We are able to partially work around this (during the initial creation of an `azurerm_virtual_network`) by using a `local-exec` provisioner that calls the command shown below. That said, it would be much nicer if this could be fully supported for all CRUD operations.

```bash
az resource update \
  --subscription "$subscription" \
  --resource-group "$resource_group" \
  --name "$vhub_name" \
  --resource-type "Microsoft.Network/virtualHubs" \
  --add properties.virtualNetworkConnections "{
    \"name\": \"${vnet_name}_conn\",
    \"properties\": {
        \"allowHubToRemoteVnetTransit\": true,
        \"allowRemoteVnetToUseHubVnetGateways\": true,
        \"enableInternetSecurity\": true,
          \"remoteVirtualNetwork\": {
        \"id\": \"$vnet_id\"
        }
    },
    \"type\": \"Microsoft.Network/virtualHubs/hubVirtualNetworkConnections\"
  }"
```

**Comment by kpfleming** [comment]
This repository is for the GitHub provider, not the Azure provider.

**Comment by adamalex** [comment]
Ha whoops, I will move this

**Comment by adamalex** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/5613
