### ISSUE TITLE
insecure_ssl = true parameter is not working

### ISSUE THREAD

**Issue by ruzickap** [terraform-providers/terraform-provider-github#352]
### Terraform Version

```bash
$ terraform -v
Terraform v0.12.18
```

### Affected Resource(s)
- github_repository_webhook
- (maybe also github_organization_webhook)

### Terraform Configuration Files

```hcl
provider "github" {
  token        = var.prow_oauth_token
  organization = "MyOrg"
}

resource "github_repository_webhook" "prow" {
  repository = "MyRepo"

  configuration {
    url          = "https://prow.myexample.com/hook"
    content_type = "json"
    insecure_ssl = true
    secret       = var.github_webhook_prow_secret
  }

  active = true
  events = ["*"]
}
```

### Actual Behavior
The GitHub Webhook is properly created, but the "SSL Validation" is not disabled.

### Steps to Reproduce

I'm using the Terrafrom code mentioned above to create GitHub Webhook. 
In the code above you can see the I would like to disable SSL Validation by setting the parameter `insecure_ssl = true`.

The GitHub Webhook is created by Terraform properly, but the SSL Validation is not disabled - see the screenshot:

![image](https://user-images.githubusercontent.com/1434387/74318645-f2530800-4d7d-11ea-9019-66c3cd646d5c.png)

If I manually click in GitHub Web GUI to "Disable" the webhook is working fine like it should be - but I can not do it via Terraform now.

Thanks for looking at it.

**Comment by ruzickap** [comment]
Looks like there is only problem with incomplete documentation.

If I use `1` instead of `false` it's working fine:

```
insecure_ssl = "1"
```

**Comment by vikkyomkar** [comment]
@ruzickap @jcudit I will raise a PR for this issue

**Comment by jcudit** [comment]
The fix from ☝️ will land in the next release.  Thanks again to the community for documenting and fixing this bug. 🙇

**Comment by martinssipenko** [comment]
We should close this issue as it's fixed by #365 

@ruzickap can you do it please?

**Comment by ruzickap** [comment]
I checked the #365 and I'm missing the change in the documentation: https://github.com/terraform-providers/terraform-provider-github/blob/master/website/docs/index.html.markdown

It should be changed there as well...

**Comment by martinssipenko** [comment]
@ruzickap the docs already state that boolean should be used (according to examples):
https://www.terraform.io/docs/providers/github/r/repository_webhook.html

**Comment by ruzickap** [comment]
Ok... closing...
