### ISSUE TITLE
Upgrade to go-github version 29.0.3

### ISSUE THREAD

**Issue by martinssipenko** [terraform-providers/terraform-provider-github#368]
I wanted to create a pull request to upgrade go-github to version 29.0.3, however, I've stumbled across issues that I'd like to discuss prior moving forward with implementation.

The issue is that GitHub has deprecated some of the Team API endpoints (marked as Legacy [here](https://developer.github.com/v3/teams/#teams)). After this change go-github has made a braking change in version 29.0.3, where [they removed some methods](https://github.com/google/go-github/pull/1400/files) by replacing them with others methods.

This terraform provider currently uses the deleted methods in [`resource_github_team.go`](https://github.com/terraform-providers/terraform-provider-github/blob/888d8b89a1278d003af6837943783ca7c0a0699a/github/resource_github_team.go) (`GetTeam`, `EditTeam`, `DeleteTeam`) and [`resource_github_team_repository.go`](https://github.com/terraform-providers/terraform-provider-github/blob/888d8b89a1278d003af6837943783ca7c0a0699a/github/resource_github_team_repository.go) (`AddTeamRepo`, `IsTeamRepo`, `RemoveTeamRepo`).

This makes the upgrade hard because the provider code needs to be updated to use new methods of go-github, but the new methods require extra arguments. For example `AddTeamRepo` is now replaced by `AddTeamRepoByID` and `AddTeamRepoBySlug`. `AddTeamRepoByID` requires `teamId (int)` which we do have and `orgID (int)` which we don't have in state. The other method `AddTeamRepoByID` requires `orgName (string)` which we do have in provider config and `slug (string)` which we do have in state, but not as part of ID.

The situation is even trickier  with `resource_github_team_repository.go`, for example `AddTeamRepo` func is now replaced by either `AddTeamRepoByID` or `AddTeamRepoBySlug`. The `AddTeamRepoByID` requires `orgID (int)` which we don't have in state and `teamID (int)` which is passed as argument into resource. The `AddTeamRepoBySlug` requires `orgName (string)`, which we do have in provider config, and taem `slug (string)`  which we don't have available.

I'm looking for a guidence to how to solve this issue. Should we increment the schema version and use [`StateUpgraders`](https://godoc.org/github.com/hashicorp/terraform/helper/schema#StateUpgrader) to get the missing data into state? Or should we rethink the interface for affected resources?

**Comment by benj-fletch** [comment]
Hi @martinssipenko I was looking at this independently of you based on our discussion on #362. 

I have implemented a method of retrieving the `orgID (int)` as a computed value to the provider. Does this address the issues you raise with existing state?

**Comment by martinssipenko** [comment]
@benj-fletch yes, i think they do.

**Comment by arri-cc** [comment]
@martinssipenko You beat me to it, I was looking into this last night to try to solve #305.

**Comment by martinssipenko** [comment]
@arri-cc check out #369 , which will hopefully fix this issue and unblock few others.

**Comment by benj-fletch** [comment]
I think this issue can now be closed following the merge of #369 ?
