### ISSUE TITLE
Trigger acceptance test runs from PRs

### ISSUE THREAD

**Issue by jcudit** [terraform-providers/terraform-provider-github#374]
New contributors to this repository currently need to run through [these instructions](https://github.com/terraform-providers/terraform-provider-github#acceptance-test-prerequisites) before they can validate their changes are safe to merge.

I have been iterating on a branch to provide acceptance testing via a GitHub Action that can be triggered by adding a label with a specific prefix to a PR.  Since becoming usable, I have rarely needed to drop to my local setup to run tests.

This issue tracks upstreaming this Action so that the community can trigger tests on their own.

cc https://github.com/terraform-providers/terraform-provider-github/issues/350 (documents flaky tests)
cc https://github.com/terraform-providers/terraform-provider-github/pull/372 (tests require `go 1.13`)
cc https://github.com/terraformtesting/acceptance-tests

---

- [x] Publish branch for review
- [x] Await the outcome of `go 1.13` adoption
- [x] Add secrets to this repository (requires admin privs)
- [x] Merge branch

**Comment by benj-fletch** [comment]
If you haven't planned to already, I would suggest that we enable the acceptance tests to run as a requisite action to be able to merge to master. Thoughts?
(See here for further info https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks)

**Comment by jcudit** [comment]
I think that is a solid plan long term.  I'd like to use them ad-hoc initially to gain more confidence in the stability of the tests.  Good call though, I had not considered coupling them to a merge as yet.
