### ISSUE TITLE
Add a `allow_force_pushes` and `allow_deletions` to `github_branch_protection`

### ISSUE THREAD

**Issue by shunkakinoki** [terraform-providers/terraform-provider-github#387]
This is more of a nice-to-have feature I guess,
but the two options `allow_force_pushes` and `allow_deletions` are missing from the `github_branch_protection` resource.

**Comment by jcudit** [comment]
👋 it looks like this addition has been previously requested over in https://github.com/terraform-providers/terraform-provider-github/issues/305 as well and has seen some movement.

**Comment by shunkakinoki** [comment]
Oh sorry my bad! Appreciate the work! Closing it as a duplicate
