### ISSUE TITLE
required_pull_request_reviews in github_branch_protection isn't applying

### ISSUE THREAD

**Issue by gregswift** [terraform-providers/terraform-provider-github#40]
Hi there,

### Terraform Version
0.9.11 (Last time I knew this worked was 0.9.5, but we upgraded and it started having this issue)

### Affected Resource(s)
- github_branch_protection

We are seeing a similar output with the vcd_vapp.ip, but I'm not sure that its the *same* issue. We aren't seeing it with any other resources.

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "myrepo_master" {
    repository = "${github_repository.myrepo.name}"
    branch = "master"
    required_status_checks {
        include_admins = true
        strict = true
        contexts = []
    }
    required_pull_request_reviews {
        include_admins = true
    }

}
```

### Debug Output
https://gist.github.com/gregswift/5a934aa4a638701ec1a73123b84fb788 (encrypted with hashicorp gpg key)

### Panic Output
No panic

### Expected Behavior
The configuration should be set in GitHub to require reviews and include admins.

### Actual Behavior
The setting isn't taking so every time we run `terraform apply` it wants to re-apply the setting.

```
github_branch_protection.deployment-control_master: Modifying... (ID: myrepo:master)
  required_pull_request_reviews.#:                "0" => "1"
  required_pull_request_reviews.0.include_admins: "" => "true"
```

### Steps to Reproduce
1. Create github_branch_protection that matches the one above
2. `terraform apply`

### Important Factoids
This is against GitHub:Enterprise 2.8.  The vcd_vapp thing I was talking about above is that we have it set to 'allocated', which is a thing in the documetnation that has worked for a while for us, but now it keeps storing the IP in the state and wanting to change it back to 'allocated' every run. This doesnt actually change anything as far as we can tell, whichs i why it appears simiar, in that it keeps wanting to apply the change. but here it *isnt* applying the change. With vcd_vapp it seems more of a statefile handling issue.

### References
terraform-providers/terraform-provider-vcd#29 for that issue

**Comment by grubernaut** [comment]
Hey @gregswift, thanks for the issue! 

I believe #26 should contain the fix that you need. Please ping if it doesn't solve the issue you're seeing though. Thanks!

**Comment by gregswift** [comment]
@grubernaut so this wont be anywhere until 0.10 ?

**Comment by grubernaut** [comment]
@gregswift Correct, we can release v0.1.1 of the github provider (probably should do that now), and it'll be present in the latest 0.10 beta of Terraform.
