### ISSUE TITLE
Add "topic" to the repo creation 

### ISSUE THREAD

**Issue by 99** [terraform-providers/terraform-provider-github#41]
Hi there,

this is more like a feature request. I don't see in docs option to add repo topics https://github.com/blog/2309-introducing-topics.
Will appreciate if that could be added.

Natalie

**Comment by Techcadia** [comment]
https://developer.github.com/v3/repos/#list-all-topics-for-a-repository

Just adding that this is still in preview. Not sure what the thought process is on implementing preview features into a production level provider.

**Comment by thomasbrezinski** [comment]
@radeksimko if you could confirm whether supporting a preview feature would be approved, I would be happy to take a look at implementing this :)

It's been in preview since January 2017

**Comment by endorama** [comment]
Hello, I would really need this feature, and I would love to see it in terraform. 

Any update on this? I'm willing to help, if needed. Thanks

**Comment by chandy** [comment]
@radeksimko would also love to get confirmation on @thomasbrezinski question about supporting a preview feature

**Comment by paultyng** [comment]
If its in the SDK, I'd be happy to merge a PR for topic support.

Regarding preview features, we generally prefer not to support them until we can be sure an API/SDK is locked down, but seeing as topics seem pretty stable now and are also released in Github Enterprise I think it would be safe to support this feature.

**Comment by tylersmith34** [comment]
I'm interested in this as well and could help with beta/preview testing.
