### ISSUE TITLE
github_repository documentation incorrect argument for delete_branch_on_merge

### ISSUE THREAD

**Issue by deppy** [terraform-providers/terraform-provider-github#419]
[The documentation ](https://www.terraform.io/docs/providers/github/r/repository.html#auto_delete_head_branch) provides an argument called `auto_delete_head_branch` but the code calls it `delete_branch_on_merge`.

You can verify that `auto_delete_head_branch` is incorrect with:
```
resource "github_repository" "example" {
  name                                   = "example"
  description                         = "My awesome codebase"
  delete_branch_on_merge = true
}
```

and then simply run `terraform validate`

**Comment by anGie44** [comment]
hi @deppy! Just wanted to follow-up and note I'm going to close this as a recent merge of #408 addresses what you've pointed out.  Thanks for the work you put into creating the issue/PR though :)
