### ISSUE TITLE
Team sync groups data source pagination

### ISSUE THREAD

**Issue by patrickmarabeas** [terraform-providers/terraform-provider-github#455]
### Affected Resource(s)
- data_source_github_organization_team_sync_groups

### Deets
Given the data source is returning exactly 100 items (when there should probably be thousands *sad sigh*), I'm going to assert that pagination is either broken. Unsure whether it's the provider or `go-github` lib.

Given my realisation of just how much data is going to be returned, I opted to roll the `azuread` provider into my module to perform the look up based on a groups name.

**Comment by patrickmarabeas** [comment]
cc @anGie44

**Comment by anGie44** [comment]
ah thanks for catching this @patrickmarabeas! i haven't tested it out yet but it looks like this line might be responsible https://github.com/terraform-providers/terraform-provider-github/blob/91fc6ed8e5bfca2e31bed79527f82084fb146718/github/data_source_github_organization_team_sync_groups.go#L67 .. in retrospect, casting did seem questionable. i believe it should be `options.Page = resp.NextPageToken` per [docs](https://godoc.org/github.com/google/go-github/github#Response)

**Comment by anGie44** [comment]
@patrickmarabeas do you mind giving a review to the PR?

**Comment by kuwas** [comment]
For anyone needing background context, this was fixed in this PR in the go-github client:
* https://github.com/google/go-github/issues/1383
* https://github.com/google/go-github/pull/1384
