### ISSUE TITLE
Add flags allow_force_pushes & allow_force_pushes

### ISSUE THREAD

**Issue by meabed** [terraform-providers/terraform-provider-github#472]
Hi Awesomes,
Thank you so much for the great effort!
It would be great if this 2 flags could be added to the resource `github_branch_protection`
- allow_force_pushes => boolean
- allow_deletions => boolean

The API is supports in the github api in vendor.

Github reference:
https://developer.github.com/v3/repos/branches/

Thanks a lot 💌

**Comment by SanderKnape** [comment]
It looks like there is already an issue open for this: #305 

I just opened a PR to add support for this: #473
