### ISSUE TITLE
TF support for org level secrets?

### ISSUE THREAD

**Issue by curiousdev** [terraform-providers/terraform-provider-github#496]
Is there support for terraforming secrets for an github organization? I see that `github_actions_secret` could be expanded to support this.

**Comment by nikolay** [comment]
https://github.com/terraform-providers/terraform-provider-github/issues/468

**Comment by nikolay** [comment]
@curiousdev Please, close this dupe.

**Comment by jcudit** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-github/issues/468
