### ISSUE TITLE
Feature Request: Add support for enabling Dependabot on Github repos

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [terraform-providers/terraform-provider-github#511]
I have been searching high and low and have yet to find any documentation on how to enable dependabot through terraform. I can only assume that this is not a supported feature. So I would like to request that this be added.

Thanks

**Comment by MrGossett** [comment]
@rmclaughlin-nelnet I've looked through the [GitHub v3 API docs](https://docs.github.com/en/rest), and I can't find an API that would enable Dependabot. It's hard to get confirmation either way, but it looks like enabling Dependabot can only be done manually right now. Do you know if that's correct?

If there was an API to enable Dependabot, then the next step would be to expose it in the [go-github](https://github.com/google/go-github) package, which the Terraform GitHub provider uses to talk to GitHub. After that, then this provider would be in a position to add support.

**Comment by rmclaughlin-nelnet** [comment]
Looks like it may be available in the API https://docs.github.com/en/rest/reference/repos#enable-vulnerability-alerts

**Comment by rmclaughlin-nelnet** [comment]
Looks like this is a dup of https://github.com/terraform-providers/terraform-provider-github/issues/238

**Comment by jasonkarns** [comment]
was searching for this but https://github.com/terraform-providers/terraform-provider-github/issues/238 is a dead link :/
