### ISSUE TITLE
 terraform import github_membership.member <org>:<user> does not seem to work

### ISSUE THREAD

**Issue by maxandersen** [terraform-providers/terraform-provider-github#526]
### Terraform Version
Terraform v0.12.29
+ provider.github v2.9.2

### Affected Resource(s)
- github_membership.member

### Terraform Configuration Files
```hcl
resource "github_membership" "maxandersen" {
   username = "maxandersen"
   role     = "admin"
 }
```

### Debug Output
```
 TF_LOG=TRACE terraform import github_membership.member jbangdev:maxandersen
2020/08/04 15:49:55 [INFO] Terraform version: 0.12.29
2020/08/04 15:49:55 [INFO] Go runtime version: go1.13.14
2020/08/04 15:49:55 [INFO] CLI args: []string{"/usr/local/bin/terraform", "import", "github_membership.member", "jbangdev:maxandersen"}
2020/08/04 15:49:55 [DEBUG] Attempting to open CLI config file: /Users/max/.terraformrc
2020/08/04 15:49:55 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/08/04 15:49:55 [INFO] CLI command args: []string{"import", "github_membership.member", "jbangdev:maxandersen"}
Error: resource address "github_membership.member" does not exist in the configuration.

Before importing this resource, please create its configuration in the root module. For example:

resource "github_membership" "member" {
  # (resource arguments)
}
```

### Expected Behavior
The github membership should be imported as the resource is already present as requested.

### Actual Behavior
Import does not happen. error occurs.

### Important Factoids
It is weird this is having issues as it works fine for `github_repository` and `github_team`; just not `github_membership`. `terraform plan` and `terraform apply` works with membership as defined but just can't import them.

**Comment by SanderKnape** [comment]
You `terraform import github_membership.member jbangdev:maxandersen` line is incorrect. It should be `terraform import github_membership.maxandersen jbangdev:maxandersen`.

**Comment by maxandersen** [comment]
Ok, then it's a bug for the docs that states:


'terraform import github_team_membership.member 1234567:someuser'

At https://www.terraform.io/docs/providers/github/r/team_membership.html

Should then be:

'terraform import github_team_membership.someuser 1234567:someuser'

**Comment by bondezbond** [comment]
@maxandersen the docs are showing an example if the terraform resource name was called `member`. In your case the terraform resource name is `maxandersen`.

**Comment by jcudit** [comment]
Happy to review a documentation fix here to provide more clear documentation.  Please re-open if desired and we can work together to get this patched up.
