### ISSUE TITLE
Visibility not available for github_repository

### ISSUE THREAD

**Issue by gleichda** [terraform-providers/terraform-provider-github#532]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
$ terraform -v                                                                                  
Terraform v0.12.29
+ provider.github v2.9.2

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "github" {
  token        = file("/Users/gleichd/.github-token")
  organization = "XXX"
}

resource "github_repository" "repo" {
  name        = "myrepo"
  description = "my demo repo"
  auto_init   = true
  visibility  = "internal"
}
```

### Expected Behavior
According to #304 and #454 and also the [Changelog](https://github.com/terraform-providers/terraform-provider-github/blob/master/CHANGELOG.md#290-june-29-2020) the `visibility` option should be available since 2.9.0

### Actual Behavior

```shell script
terraform plan

Error: Unsupported argument

  on test.tf line 10, in resource "github_repository" "repo":
  10:   visibility  = "internal"

An argument named "visibility" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Is there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #304 
- #454

**Comment by jcudit** [comment]
I _think_ this has already been addressed?  See [this example](https://github.com/terraform-providers/terraform-provider-github/tree/master/examples/repository_visibility).  Please re-open if I've misunderstood.
