### ISSUE TITLE
feature request: webhook url can be sensitive

### ISSUE THREAD

**Issue by kzw** [terraform-providers/terraform-provider-github#535]
Would it be acceptable to make repo webhook url as sensitive?  I think 

https://github.com/terraform-providers/terraform-provider-github/compare/master...kzw:master

will do it.

We have repo webhooks to our atlantis server and that webhook url contain basic auth credentials and we do not want this in the CICD logs which contain `terraforrm plan` output.

**Comment by kzw** [comment]
i submitted a PR https://github.com/terraform-providers/terraform-provider-github/pull/540

**Comment by majormoses** [comment]
I am not a maintainer, I think they will accept it. As I commented on the PR updating the docs on the rationale will help the maintainers and future users understand why this makes sense.

**Comment by jcudit** [comment]
https://github.com/terraform-providers/terraform-provider-github/pull/540 has shipped.
