### ISSUE TITLE
How to force the github provider to use v4 graphql api

### ISSUE THREAD

**Issue by tru2dagame** [terraform-providers/terraform-provider-github#551]
Hi there,

### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/github v3.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection

### Terraform Configuration Files
```hcl
provider "github" {
  organization = "xxxx"
  token = "xxxxxxxxxxxxxxx"
  base_url = "https://git.xxxxxxx.xxxxx/"
}

terraform {
  required_providers {
    github = {
      source = "hashicorp/github"
      version = "= 3.0.0"
    }
  }
  required_version = "= 0.13.2"
}


resource "github_branch_protection" "ud_alpha" {
  repository     = "xxxxxx"
  branch         = "alpha"
  enforce_admins = true


  required_pull_request_reviews {
    required_approving_review_count = 1
  }
}

```

### Debug Output
![image](https://user-images.githubusercontent.com/1673006/93303368-ece70000-f82d-11ea-86e7-a67c83d8b97c.png)

### Expected Behavior
v4 graphql api could protect a non-existent git branch 

### Actual Behavior
```
Error: PUT https://git.xxxx.xxxx/api/v3/repos/xxxx/xxxxxxxx/branches/alpha/protection: 404 Branch not found []
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### References

- #337 
- #167

**Comment by majormoses** [comment]
Hey I think its just a matter of defining another github provider and then passing that to specific resource/module invocations like so: https://github.com/terraform-providers/terraform-provider-github/issues/167#issuecomment-606375836
```tf
provider "github" {
  organization = "myorg"
  ...
}

provider "github-v4" {
  organization = "myorg"
  ...
}

resource "github_branch_protection" "master" {
  provider = github-v4 # defaults to github
  ...
}
```

**Comment by tru2dagame** [comment]
Hi @majormoses,

Thanks for the help. I have tried that. I don't quite under how to use "github-v4" like that. I got this error:
```
Provider "github-v4" not available for installation.

A provider named "github-v4" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".
```

**Comment by tru2dagame** [comment]
Hi @majormoses, 

Thanks for the help. 

That custom provider is base on version 2. 
The terraform github provider is now version 3.
There will be some errors downgrade the provider to version 2.

**Comment by tru2dagame** [comment]
OK. I found the [master branch](https://github.com/terraform-providers/terraform-provider-github/blob/3bc761a67b61f8958d59033c74255011cfff5a03/github/util_v4_branch_protection.go) has switch branch protection to v4 but not tag v3.0.0. 

Tried to build the master branch locally got this error:
```
==> Checking that code complies with gofmt requirements...
go install
# github.com/terraform-providers/terraform-provider-github/github
github/resource_github_repository.go:305:6: undefined: err
github/resource_github_repository.go:305:43: undefined: orgName
github/resource_github_repository.go:306:6: undefined: err
github/resource_github_repository.go:307:11: undefined: err
github/resource_github_repository.go:379:81: undefined: orgName
github/resource_github_repository.go:449:43: undefined: orgName
gnumake: *** [build] Error 2
```

**Comment by mallyvai** [comment]
https://github.com/terraform-providers/terraform-provider-github/issues/555

**Comment by jcudit** [comment]
Confirmed that the implementation for this resource has changed to the v4 GraphQL API.  There is ongoing discussion around supporting both previous and current implementations going forward over in https://github.com/terraform-providers/terraform-provider-github/issues/606, but not sure how it will turn out.

I'm not sure if this issue is still relevant, but please reopen and clarify what can be helped with if I've misunderstood.
