### ISSUE TITLE
Provider broken again

### ISSUE THREAD

**Issue by analytically** [terraform-providers/terraform-provider-github#552]
Again this provider is broken, I migrated our setup from 2.9.1 (GH 2.20.7) to 2.9.2 (GH 2.21.5) and everything worked. Today it seems like 3.0.0 is released (even not officially on this site?) and again errors; what a mess.

Error: GET https://redacted/login?return_to=https%3A%2F%2Fredacted%2Fapi%2Fapi%2Fv3%2Frepos%2Fgc%2Fredacted: 406  []
Error: GET https://redacted/login?return_to=https%3A%2F%2Fredacted%2Fapi%2Fapi%2Fv3%2Frepos%2Fgc%2Fredacted: 406  []

Error: This resource can only be used in the context of an organization, "redacted" is a user.

redacted -> our domain/org.

This is been the latest in many failed upgrades.

**Comment by skyzyx** [comment]
With semantic versioning, a new major version signals breaking changes by design.

That said, this is definitely a bug with the `GITHUB_TOKEN` environment variable now being treated as anonymous whereas it wasn't before. TBH, 3.x has been a mess.
