### ISSUE TITLE
Commit a4eb4faf494171f1eeef70af5ceb0ed6258b7d02 breaks build

### ISSUE THREAD

**Issue by mallyvai** [terraform-providers/terraform-provider-github#555]
Hi there,
This PR reverts the buggy commit: https://github.com/terraform-providers/terraform-provider-github/pull/554

### Expected Behavior
```
 ~/Code/go/src/github.com/mallyvai/terraform-provider-github   mallyvai-revert-bad-commit  make
==> Checking that code complies with gofmt requirements...
go install
```

### Actual Behavior
``` ~/Code/go/src/github.com/mallyvai/terraform-provider-github   master  make
==> Checking that code complies with gofmt requirements...
go install
# github.com/terraform-providers/terraform-provider-github/github
github/resource_github_repository.go:305:6: undefined: err
github/resource_github_repository.go:305:43: undefined: orgName
github/resource_github_repository.go:306:6: undefined: err
github/resource_github_repository.go:307:11: undefined: err
github/resource_github_repository.go:379:81: undefined: orgName
github/resource_github_repository.go:449:43: undefined: orgName
make: *** [build] Error 2
```
### Steps to Reproduce
1. Checkout this repo
2. Run `make`

### Important Factoids
Running on OS X Catalina 10.15.6 with go version 1.15.2

**Comment by jcudit** [comment]
Apologies on this one.  At the time I was unaware that there are projects depending on the default branch being in a buildable state.  I had been assuming consumers were using releases instead.  Will be more careful with the state of things that merge going forward, although this limits flexibility when working async on PRs.
