### ISSUE TITLE
Import a full org setup

### ISSUE THREAD

**Issue by AvnerCohen** [terraform-providers/terraform-provider-github#583]
(Excuse me for skipping the template, this is a simple case of doc suggestion, feel free to just close if not relevant)

Migrating an existing org, with many repos and existing teams setup is, I am sure, a common use case that is really nicely solved with:
https://github.com/chrisanthropic/terraform-import-github-organization

At the very least, I suggest to add to readme a note about this project (happy to PR if this makes sense).

If there is a nice way to import that using the provider, I suspect it's not an easy to find in the docs, happy to contribute there too, with a relevant pointer.

**Comment by jcudit** [comment]
🤔 maybe we add a new md file with recommended tooling / examples. I've had other projects reach out in the past as well. Happy to review a PR related to this effort if you'd like to get one started 😀

**Comment by AvnerCohen** [comment]
Closing this for now, referenced project is a bit stale, so not sure I can whole heartily recommend this in the official TF repo.
Maybe this issue in and of itself will help someone at some future.
