### ISSUE TITLE
[FEATURE REQUEST] Data resource for query all repositories in a Github ORG

### ISSUE THREAD

**Issue by mechastorm** [terraform-providers/terraform-provider-github#61]
It would be useful if there was a terraform data resource to query the github org - specifically get a list of all repositories from the Github Org (or maybe even a user).  

example

```hcl
# Get all repositories that are part of example org 
data "github_repos" "example" {
  slug = "example-org"
}

# Get all repositories that are part of example user 
data "github_repos" "example" {
  slug = "example-user"
}
```

Using the output from that data resource, we can then iterate over them for actions like
- attaching teams to a repository
- setting a standardized `github_branch_protection` setting on all repositories.

**Comment by radeksimko** [comment]
Hi @mechastorm 
thanks for opening this issue.

I'm thinking we could implement this on top of the [Search API](https://developer.github.com/v3/search/#search-repositories) which would give users the flexibility to query any repositories, whether scoped by an org, name, or anything else using [the search syntax](https://help.github.com/articles/understanding-the-search-syntax/).

e.g.

```hcl
data "github_repositories" "example" {
  search_query = "user:terraform-providers language:Go"
}

output "full_names" {
  value = "${data.github_repositories.example.full_names}"
}
```
```
full_names = [
  "terraform-providers/terraform-provider-aws",
  "terraform-providers/terraform-provider-azurerm",
  "terraform-providers/terraform-provider-google",
...
]
```

then if users need they can leverage the other data source (to get more data about each repository) which was merged recently:

```hcl
data "github_repositories" "example" {
  search_query = "user:terraform-providers language:Go"
}

data "github_repository" "provider" {
  count     = "${length(data.github_repositories.providers.full_names)}"
  full_name = "${data.github_repositories.providers.full_names[count.index]}"
}

output "clone_urls" {
  value = "${data.github_repository.provider.*.ssh_clone_url}"
}
```
```
clone_urls = [
    git@github.com:terraform-providers/terraform-provider-vault.git,
    git@github.com:terraform-providers/terraform-provider-github.git,
    git@github.com:terraform-providers/terraform-provider-cloudflare.git,
...
]
```

or manage team permissions:

```hcl
data "github_repositories" "example" {
  search_query = "user:terraform-providers language:Go"
}

resource "github_team_repository" "some_team_repo" {
  count     = "${length(data.github_repositories.providers.names)}"

  team_id    = "${github_team.example.id}"
  repository = "${data.github_repositories.providers.names[count.index]}"
  permission = "pull"
}
```

What do you think? Would that satisfy your use cases?
