### ISSUE TITLE
github_branch_protection won't run over version 3.0

### ISSUE THREAD

**Issue by semperfitodd** [terraform-providers/terraform-provider-github#618]
### Terraform Version
0.14.0

### Affected Resource(s)
Please list the resources as a list, for example:
github_branch_protection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "github_branch_protection" "main" {
  count = length(var.branches_to_protect)

  repository = github_repository.main.name
  branch     = var.branches_to_protect[count.index]

  enforce_admins = true

  required_status_checks {
    strict   = var.strict_status_check
    contexts = var.required_status_checks
  }

  required_pull_request_reviews {
    dismiss_stale_reviews = true
  }
}
```

### Debug Output
Error: Unsupported argument

  on modules/github/github.tf line 83, in resource "github_branch_protection" "main":
  83:   branch     = var.branches_to_protect[count.index]

An argument named "branch" is not expected here

Error: Unsupported argument

  on modules/github/github.tf line 83, in resource "github_branch_protection" "main":
  83:   branch     = var.branches_to_protect[count.index]

An argument named "branch" is not expected here..

### Expected Behavior
apply branch protection resource

### Actual Behavior
Errored as shown above

### Steps to Reproduce
terraform plan

### Important Factoids
The documentation states "branch" as a required argument. TF of any version 0.13.xx and 0.14.xx hates it. Not sure if the documentation needs to be updated.

**Comment by kzw** [comment]
The documentation in this repo is up-to-date but https://www.terraform.io/docs/providers/github/index.html is outdated

**Comment by jcudit** [comment]
Are `v3.1.0` / `v4.0.0` options for your use case? The `branch` argument changed to `pattern` in these versions and onwards.  See the [CHANGELOG](https://github.com/terraform-providers/terraform-provider-github/blob/master/CHANGELOG.md#400-november-10-2020) for details.

The docs are [temporarily out of date](https://github.com/terraform-providers/terraform-provider-github/issues/595) at the moment but there is a plan to get them aligned going forward.

**Comment by semperfitodd** [comment]
Looks like changing branch and repository arguments worked this out.
