### ISSUE TITLE
Keeping terraform documentation in sync

### ISSUE THREAD

**Issue by colltoaction** [terraform-providers/terraform-provider-github#640]
Hi! I'm looking at the releases page and noted that https://www.terraform.io/docs/providers/github is not in sync with this repository. Is there any way I can help with that?

**Comment by jcudit** [comment]
This is being tracked over in https://github.com/terraform-providers/terraform-provider-github/issues/595 and is currently blocked on migrating this project to the Terraform Registry.  Apologies on the degraded experience during this transition.
