### ISSUE TITLE
support archived repositories

### ISSUE THREAD

**Issue by majuscule** [terraform-providers/terraform-provider-github#73]
### Terraform Version
`Terraform v0.11.0`

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository

### Terraform Configuration Files

i.e.:
```hcl
resource "github_repository" "project.beta" {
  name        = "project.beta"
  description = "outdated project - see product.v1"

  archived    = True
}
```

![screen shot 2018-02-12 at 11 27 52 am](https://user-images.githubusercontent.com/187737/36107374-c8ae483c-0fe7-11e8-923b-2bf501f82f07.png)

**Comment by radeksimko** [comment]
Hi @majuscule 
support for archiving was added in https://github.com/terraform-providers/terraform-provider-github/pull/64 which was released as part of `1.1.0` on the 11th May.

For that reason I'm going to close this issue.

Thanks.
