### ISSUE TITLE
Support label descriptions for github_issue_label resource

### ISSUE THREAD

**Issue by petomalina** [terraform-providers/terraform-provider-github#76]
Github allows users to create labels with descriptions. This functionality is missing from the issue_label resource.

https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

**Comment by gelidus** [comment]
Update: it looks like this will be blocked until the public API is released:
https://github.com/google/go-github/issues/856
https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/

**Comment by paultyng** [comment]
Yep, I subscribed to that upstream issue (google/go-github#856),  will keep an eye on it, thanks for bringing this up.

**Comment by tdmalone** [comment]
Just a note that it looks like this has now been implemented in go-github :)

**Comment by paultyng** [comment]
Yep, we'll need to update the vendored version, but this is ready to be added!
