### ISSUE TITLE
github_repository_webhook secret always generates an "update in-place"

### ISSUE THREAD

**Issue by enobrev** [terraform-providers/terraform-provider-github#81]
### Terraform Version
Terraform v0.11.5
+ provider.github v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- github_repository_webhook

### Terraform Configuration Files
```hcl

provider "github" {
    token        = "${var.github_token}"
    organization = "${var.github_organization}"
}

resource "github_repository_webhook" "example" {
    repository = "example"
    name       = "web"
    active     = true
    events     = ["push"]
  
    configuration {
        url          = "https://example.com"
        content_type = "json"
        secret       = "This is a secret"
        insecure_ssl = 0
    }
}
```

### Debug Output
This gist shows three commands.  `plan`, `apply`, and `plan` again.  The first two create a new webhook with a secret.  The last `plan` shows that it wants to overwrite the secret.

https://gist.github.com/enobrev/0d574a7e396e4a0b81ec1851b21e812c

### Expected Behavior
```bash
No changes. Infrastructure is up-to-date.
```

I'm not sure how this is generally handled, where we cannot confirm the remote value on the provider with what was set in the template, but generating a new "update in-place" every time terraform is run isn't ideal.

### Actual Behavior
```bash
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ github_repository_webhook.example
      configuration.secret: "********" => "This is a secret"

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a `github_repository_webhook` with `configuration.secret` set to any string (besides "********")
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

### Assumptions
Since the github api will return "********" instead of the actual password, terraform will compare what's returned by the api and what's set in the template, and since there's a difference, try to write what's in the template.

### References
https://developer.github.com/v3/repos/hooks/

### Workarounds
For the time being, I've been creating webhooks with the correct `configuration.secret`, and then after it's been "applied", I change the value in of `configuration.secret` my template to "********".

**Comment by radeksimko** [comment]
@enobrev Reproduced, thanks for the report.

I'm working on a fix.
