### ISSUE TITLE
[Feature Request] support requiring "signed commits" on `github_branch_protection`

### ISSUE THREAD

**Issue by majormoses** [terraform-providers/terraform-provider-github#87]
### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection

### Important Factoids
Some organizations require commits to be signed to verify identity of submitter for legal reasons.

It is available in the rest api: https://developer.github.com/v3/repos/branches/#add-required-signatures-of-protected-branch but I do not see it yet in the upstream go library: https://github.com/google/go-github/blob/v15.0.0/github/repos.go so we are blocked until it is added. I have created https://github.com/google/go-github/issues/902 upstream to track.

![image](https://user-images.githubusercontent.com/3145127/39390795-bb3c6944-4a4e-11e8-962f-c84e4f7bea12.png)

**Comment by radeksimko** [comment]
Related: https://github.com/google/go-github/pull/880 (PR adding upstream SDK support)

**Comment by majormoses** [comment]
The functionality has been merged upstream into master but has not been released yet.

**Comment by travispaul** [comment]
Hi @majormoses, are you aware of an ETA for the next release?

Thanks in advance.

**Comment by majormoses** [comment]
It looks like its present in the latest version: https://github.com/google/go-github/tree/v19.1.0
