### ISSUE TITLE
[Feature Request] support `required_approving_review_count`

### ISSUE THREAD

**Issue by majormoses** [terraform-providers/terraform-provider-github#89]
### Affected Resource(s)
Please list the resources as a list, for example:
- github_branch_protection

### Important Factoids
Some teams are large enough that they want multiple reviewers approving it before allowing it to merge.

It is available via the [rest api](https://developer.github.com/v3/repos/branches/#update-branch-protection) but I do not see it yet in the upstream go library](https://github.com/google/go-github/blob/v15.0.0/github/repos.go) so we are blocked until that is added. I have created https://github.com/google/go-github/issues/905 to track.

![image](https://user-images.githubusercontent.com/3145127/39460306-5ecd46d6-4cb7-11e8-9a54-e1a195466920.png)

**Comment by radeksimko** [comment]
Related: https://github.com/google/go-github/pull/880 (PR adding upstream SDK support)

**Comment by victoryNap** [comment]
We're just waiting on one more review before merging.

**Comment by toddbluhm** [comment]
Just FYI, the go-github library appears to have been updated now and that PR merged in.

**Comment by harlowja** [comment]
any update on this?

**Comment by wenbin1989** [comment]
hey is this done yet? it's really a necessary feature

**Comment by paultyng** [comment]
`2.0.0` has been released, including support for this attribute.
